apiVersion: apps/v1
kind: Deployment
metadata:
  name: bp-info-app
  labels:
    app: bpinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpinfo
  template:
    metadata:
      labels:
        app: bpinfo
    spec:
      containers:
        - image:  {{ .Values.bpinfoservice.imageVersion }}/eadca2/bpinfoservice:{{ .Values.bpinfoservice.imageVersion }}
          name: bpinfoapp
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.bpinfoservice.containerPort }}
