apiVersion: v1
kind: Service
metadata:
  # The unique Service instance/name
  name: bpinfosvc
spec:
  # Add external load balancer
  # *Only supported by some cloud providers*
  type: ClusterIP
  ports:
    - name: http
      port: 22137
      targetPort: 22137
  selector:
    # this label selector
    app: bpinfo
